//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basketball
    {
        public string UserID { get; set; }
        public int SportID { get; set; }
        public Nullable<int> P_YDS { get; set; }
        public Nullable<int> R_YDS { get; set; }
        public Nullable<int> Tot_TDs { get; set; }
        public Nullable<int> Tot_Sacks { get; set; }
        public Nullable<int> RU_YDs { get; set; }
        public Nullable<int> Tot_PTS { get; set; }
        public Nullable<int> Tot_Tcks { get; set; }
        public Nullable<int> Tot_YDs { get; set; }
        public Nullable<int> Tot_Ints { get; set; }
    }
}
