//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachDetail
    {
        public string UserID { get; set; }
        public int UserType { get; set; }
        public string Contact_No { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public int SportID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public string AssistantCoach { get; set; }
        public string SchoolDivision { get; set; }
        public Nullable<int> SessionCost { get; set; }
        public Nullable<int> SessionHours { get; set; }
        public string Experience { get; set; }
    }
}
