//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExploreDBEntities : DbContext
    {
        public ExploreDBEntities()
            : base("name=ExploreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Basketball> Basketballs { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<CoachDetail> CoachDetails { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Football> Footballs { get; set; }
        public DbSet<PlayerDetail> PlayerDetails { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
    }
}
