//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Football
    {
        public string UserID { get; set; }
        public int SportID { get; set; }
        public Nullable<double> PTS { get; set; }
        public Nullable<double> FG { get; set; }
        public Nullable<double> FT { get; set; }
        public Nullable<double> TP { get; set; }
        public Nullable<double> RBS { get; set; }
        public Nullable<double> AST { get; set; }
        public Nullable<double> STL { get; set; }
        public Nullable<double> BLK { get; set; }
        public Nullable<double> MIN { get; set; }
    }
}
