//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lst_Asst_Coach
    {
        public int Asst_Coach_id { get; set; }
        public string head_Coach_Email { get; set; }
        public string Asst_Coach_name { get; set; }
    }
}
