//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Player
    {
        public int play_id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Sport { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Position { get; set; }
        public string Height { get; set; }
        public string playWeight { get; set; }
        public string Wingspan { get; set; }
        public string Experience { get; set; }
        public string Addrss { get; set; }
        public string Pass { get; set; }
        public string Image_path { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string play_State { get; set; }
        public string country { get; set; }
        public string SchoolName { get; set; }
        public string Club { get; set; }
        public string ACT { get; set; }
        public string Grade_avg { get; set; }
        public string DocumntPath { get; set; }
    }
}
